Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init-local' at Sun, 16 Aug 2020 10:05:02 +0000. Up 6.71 seconds.
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Aug 16 10:05:02 cloud-init[2446]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Aug 16 10:05:02 cloud-init[2446]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Aug 16 10:05:02 cloud-init[2446]: __init__.py[DEBUG]: Searching for data source in: []
Aug 16 10:05:02 cloud-init[2446]: cloud-init[DEBUG]: No local datasource found
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Aug 16 10:05:02 cloud-init[2446]: util.py[DEBUG]: cloud-init mode 'init' took 0.055 seconds (0.05)
Aug 16 10:05:02 cloud-init[2452]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init' at Sun, 16 Aug 2020 10:05:02 +0000. Up 6.91 seconds.
Aug 16 10:05:02 cloud-init[2452]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Aug 16 10:05:02 cloud-init[2452]: util.py[DEBUG]: Running command ['ifconfig', '-a'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:02 cloud-init[2452]: util.py[DEBUG]: Running command ['netstat', '-rn'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:02 cloud-init[2452]: cloud-init[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Aug 16 10:05:02 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/data/no-net (quiet=False)
Aug 16 10:05:02 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Aug 16 10:05:02 cloud-init[2452]: cloud-init[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Aug 16 10:05:02 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Searching for data source in: ['DataSourceEc2']
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/ec2/meta-data (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Aug 16 10:05:03 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/api/token' with {'url': 'http://169.254.169.254/latest/api/token', 'headers': {'X-aws-ec2-metadata-token-ttl-seconds': '21600'}, 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/api/token (200, 56b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/user-data' with {'url': 'http://169.254.169.254/latest/user-data', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/user-data (200, 3182b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/' with {'url': 'http://169.254.169.254/latest/meta-data/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ (200, 305b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ (200, 13b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/ebs1' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/ebs1', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ebs1 (200, 5b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/root', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/' with {'url': 'http://169.254.169.254/latest/meta-data/events/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/ (200, 12b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254/latest/meta-data/events/maintenance/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/maintenance/ (200, 17b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254/latest/meta-data/events/maintenance/scheduled', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254/latest/meta-data/events/maintenance/history', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/maintenance/history (200, 2b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/' with {'url': 'http://169.254.169.254/latest/meta-data/iam/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/ (200, 26b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/info' with {'url': 'http://169.254.169.254/latest/meta-data/iam/info', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/info (200, 216b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254/latest/meta-data/identity-credentials/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/identity-credentials/ (200, 4b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/ (200, 7b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/vhostmd', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/' with {'url': 'http://169.254.169.254/latest/meta-data/network/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/ (200, 11b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/ (200, 230b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/ipv4-associations/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/ipv4-associations/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/ipv4-associations/ (200, 13b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/ipv4-associations/54.88.121.232' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/ipv4-associations/54.88.121.232', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/ipv4-associations/54.88.121.232 (200, 12b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/local-hostname (200, 28b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/security-groups (200, 56b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/public-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/public-hostname (200, 41b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-ipv4-cidr-blocks', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/subnet-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/subnet-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/subnet-id (200, 15b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/public-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/public-ipv4s', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/public-ipv4s (200, 13b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/interface-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/interface-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/interface-id (200, 21b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/mac' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/mac (200, 17b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/security-group-ids' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/security-group-ids', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/security-group-ids (200, 20b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/local-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/local-ipv4s', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/local-ipv4s (200, 12b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/owner-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/owner-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/owner-id (200, 12b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/subnet-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/device-number' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/device-number', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/device-number (200, 1b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0a:fc:4e:4d:0a:61/vpc-id (200, 12b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/' with {'url': 'http://169.254.169.254/latest/meta-data/placement/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/ (200, 45b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/region' with {'url': 'http://169.254.169.254/latest/meta-data/placement/region', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/region (200, 9b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/latest/meta-data/placement/availability-zone', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/availability-zone (200, 10b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254/latest/meta-data/placement/availability-zone-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/' with {'url': 'http://169.254.169.254/latest/meta-data/services/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/ (200, 16b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/domain' with {'url': 'http://169.254.169.254/latest/meta-data/services/domain', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/domain (200, 13b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/partition' with {'url': 'http://169.254.169.254/latest/meta-data/services/partition', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/partition (200, 3b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/profile' with {'url': 'http://169.254.169.254/latest/meta-data/profile', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/profile (200, 11b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/local-ipv4', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-ipv4 (200, 12b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/reservation-id' with {'url': 'http://169.254.169.254/latest/meta-data/reservation-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/reservation-id (200, 19b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-hostname (200, 28b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/security-groups (200, 56b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254/latest/meta-data/instance-life-cycle', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-life-cycle (200, 9b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/latest/meta-data/ami-launch-index', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-launch-index (200, 1b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/public-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-hostname (200, 41b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/hostname' with {'url': 'http://169.254.169.254/latest/meta-data/hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/hostname (200, 28b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-id' with {'url': 'http://169.254.169.254/latest/meta-data/ami-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-id (200, 21b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-action' with {'url': 'http://169.254.169.254/latest/meta-data/instance-action', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-action (200, 4b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/mac' with {'url': 'http://169.254.169.254/latest/meta-data/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/mac (200, 17b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/public-ipv4', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-ipv4 (200, 13b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/latest/meta-data/ami-manifest-path', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-type' with {'url': 'http://169.254.169.254/latest/meta-data/instance-type', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-type (200, 8b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 19b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity (200, 33b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/document', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/document (200, 476b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 (200, 1118b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/signature', 'headers': {'X-aws-ec2-metadata-token': 'AQAAAJ2VLlmglyktCHdrBIPAwDiLX7M_Uc6aCNRkvh5eWlnThlrs5w=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Aug 16 10:05:03 cloud-init[2452]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Aug 16 10:05:03 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Crawl of metadata service took 0 seconds
Aug 16 10:05:03 cloud-init[2452]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 553 bytes from /etc/cloud/cloud.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 553 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0cbeb4542379eddc1'
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0cbeb4542379eddc1/datasource (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/datasource - wb: [644] 29 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: cloud-init[DEBUG]: init will now be targeting instance id: i-0cbeb4542379eddc1
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 553 bytes from /etc/cloud/cloud.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 553 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12048 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/user-data.txt - wb: [600] 3182 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 105 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/user-data.txt.i - wb: [600] 3241 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/vendor-data.txt - wb: [600] 4 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/vendor-data.txt.i - wb: [600] 345 bytes
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/consume_data - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/consume_data'>)
Aug 16 10:05:03 cloud-init[2452]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: {'Content-Transfer-Encoding': '7bit', 'Content-Type': 'text/cloud-config; charset="us-ascii"', 'Content-Disposition': 'attachment; filename="cloud-config.txt"', 'MIME-Version': '1.0'}
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 105 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: {'Content-Transfer-Encoding': '7bit', 'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'Content-Disposition': 'attachment; filename="user-data.txt"', 'MIME-Version': '1.0'}
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 2532 bytes
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/cloud-config.txt - wb: [600] 155 bytes
Aug 16 10:05:03 cloud-init[2452]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: no vendordata from datasource
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 553 bytes from /etc/cloud/cloud.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 553 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 155 bytes from /var/lib/cloud/instance/cloud-config.txt
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 155 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 155 bytes from /var/lib/cloud/instance/cloud-config.txt
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Attempting to load yaml from string of length 155 with allowed root types (<type 'dict'>,)
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Aug 16 10:05:03 cloud-init[2452]: stages.py[INFO]: Skipping modules ['resolv-conf'] because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f757e008b50>)
Aug 16 10:05:03 cloud-init[2452]: cc_migrator.py[DEBUG]: Migrating semaphores which are not named canonically.
Aug 16 10:05:03 cloud-init[2452]: cc_migrator.py[DEBUG]: Looking at consume_data
Aug 16 10:05:03 cloud-init[2452]: cc_migrator.py[DEBUG]: Searching for legacy per-instance semaphores under /var/lib/cloud/sem
Aug 16 10:05:03 cloud-init[2452]: cc_migrator.py[DEBUG]: Migrating semaphores which have been renamed or split.
Aug 16 10:05:03 cloud-init[2452]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem
Aug 16 10:05:03 cloud-init[2452]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/sem
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_rsyslog - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_rsyslog'>)
Aug 16 10:05:03 cloud-init[2452]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f757e008bd0>)
Aug 16 10:05:03 cloud-init[2452]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_write_files - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_write_files'>)
Aug 16 10:05:03 cloud-init[2452]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_write_metadata - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_write_metadata'>)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 9 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f757e008ad0>)
Aug 16 10:05:03 cloud-init[2452]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/2452/mountinfo (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 528 bytes from /proc/2452/mountinfo
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: resize_devices took 0.030 seconds
Aug 16 10:05:03 cloud-init[2452]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f757e008b90>)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/2452/mountinfo (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 528 bytes from /proc/2452/mountinfo
Aug 16 10:05:03 cloud-init[2452]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 53 bytes from /proc/1/environ
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 1303 bytes from /proc/self/status
Aug 16 10:05:03 cloud-init[2452]: cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Forked child 2487 who will run callback log_time
Aug 16 10:05:03 cloud-init[2452]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=ext4, val=noblock)
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_set_hostname - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_set_hostname'>)
Aug 16 10:05:03 cloud-init[2452]: cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set-hostname
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f757dc9cc50>)
Aug 16 10:05:03 cloud-init[2452]: cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update-hostname
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f757dc9cc90>)
Aug 16 10:05:03 cloud-init[2452]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_resolv_conf - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_resolv_conf'>)
Aug 16 10:05:03 cloud-init[2452]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_users_groups - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_users_groups'>)
Aug 16 10:05:03 cloud-init[2452]: __init__.py[INFO]: User ec2-user already exists, skipping.
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Running command ['usermod', '-L', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:03 cloud-init[2487]: util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:03 cloud-init[2487]: util.py[DEBUG]: backgrounded Resizing took 0.006 seconds
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Read 3729 bytes from /etc/sudoers
Aug 16 10:05:03 cloud-init[2452]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_ssh - wb: [644] 20 bytes
Aug 16 10:05:03 cloud-init[2452]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_ssh'>)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=False)
Aug 16 10:05:03 cloud-init[2452]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=False)
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=False)
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 500:500
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 500:500
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Read 565 bytes from /root/.ssh/authorized_keys
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 565 bytes
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Aug 16 10:05:04 cloud-init[2452]: cloud-init[DEBUG]: Ran 13 modules with 0 failures
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Aug 16 10:05:04 cloud-init[2452]: util.py[DEBUG]: cloud-init mode 'init' took 1.152 seconds (1.16)
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:config' at Sun, 16 Aug 2020 10:05:04 +0000. Up 8.21 seconds.
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_mounts - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_mounts'>)
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Aug 16 10:05:04 cloud-init[2506]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Aug 16 10:05:04 cloud-init[2506]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: changed swap => None
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Aug 16 10:05:04 cloud-init[2506]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount ephemeral0
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Aug 16 10:05:04 cloud-init[2506]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount swap
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: no need to setup swap
Aug 16 10:05:04 cloud-init[2506]: cc_mounts.py[DEBUG]: No modifications to fstab needed.
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_locale - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_locale'>)
Aug 16 10:05:04 cloud-init[2506]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Reading from /etc/sysconfig/i18n (quiet=False)
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Read 17 bytes from /etc/sysconfig/i18n
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /etc/sysconfig/i18n - wb: [644] 17 bytes
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_set_passwords - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_set_passwords'>)
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Aug 16 10:05:04 cloud-init[2506]: cc_set_passwords.py[DEBUG]: Replacing auth line 65 with no
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [644] 3935 bytes
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Running command ['service', 'sshd', 'status'] with allowed return codes [0] (shell=False, capture=True)
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_yum_configure - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_yum_configure'>)
Aug 16 10:05:04 cloud-init[2506]: cc_yum_configure.py[DEBUG]: Generating default repo files
Aug 16 10:05:04 cloud-init[2506]: __init__.py[DEBUG]: filtered distro mirror info: {'regional': u'repo.us-east-1.amazonaws.com'}
Aug 16 10:05:04 cloud-init[2506]: cc_yum_configure.py[DEBUG]: Using mirror: repo.us-east-1.amazonaws.com
Aug 16 10:05:04 cloud-init[2506]: cc_yum_configure.py[INFO]: Setting yum releasever to 2018.03
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /etc/yum.conf - wb: [644] 1065 bytes
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_yum_add_repo - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_yum_add_repo'>)
Aug 16 10:05:04 cloud-init[2506]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_package_update_upgrade_install'>)
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_timezone - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_timezone'>)
Aug 16 10:05:04 cloud-init[2506]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_puppet.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_puppet - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_puppet'>)
Aug 16 10:05:04 cloud-init[2506]: cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f9c3a599850>)
Aug 16 10:05:04 cloud-init[2506]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Aug 16 10:05:04 cloud-init[2506]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_runcmd - wb: [644] 20 bytes
Aug 16 10:05:04 cloud-init[2506]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0cbeb4542379eddc1/sem/config_runcmd'>)
Aug 16 10:05:04 cloud-init[2506]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Aug 16 10:05:04 cloud-init[2506]: cloud-init[DEBUG]: Ran 10 modules with 0 failures
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Aug 16 10:05:04 cloud-init[2506]: util.py[DEBUG]: cloud-init mode 'modules' took 0.216 seconds (0.22)
Aug 16 10:05:06 cloud-init[2691]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:final' at Sun, 16 Aug 2020 10:05:06 +0000. Up 10.17 seconds.
Aug 16 10:05:06 cloud-init[2691]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Aug 16 10:05:06 cloud-init[2691]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency always
Aug 16 10:05:06 cloud-init[2691]: helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f49de032e10>)
Aug 16 10:05:06 cloud-init[2691]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=True, capture=False)
Aug 16 10:05:56 cloud-init[2691]: cloud-init[DEBUG]: Ran 1 modules with 0 failures
Aug 16 10:05:56 cloud-init[2691]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Aug 16 10:05:56 cloud-init[2691]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Aug 16 10:05:56 cloud-init[2691]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Aug 16 10:05:56 cloud-init[2691]: util.py[DEBUG]: cloud-init mode 'modules' took 50.662 seconds (50.19)
